steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/consumer', './consumer' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/transcriber', './transcriber' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/producer', './producer' ]
    waitFor: ['-']

images: [
  'gcr.io/$PROJECT_ID/consumer',
  'gcr.io/$PROJECT_ID/transcriber',
  'gcr.io/$PROJECT_ID/producer'
]
