apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 2
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: gcr.io/simple-project-293220/consumer:latest
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --redisHost=10.35.210.180
            - --host=0.0.0.0
            - --port=8080
            - --id=$(PODNAME)
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP
